apiVersion: v1
kind: Pod
metadata:
  name: database-app
  namespace: k8squest
spec:
  containers:
  - name: postgres
    image: postgres:latest
    env:
    - name: POSTGRES_PASSWORD
      value: "mysecretpassword"
    ports:
    - containerPort: 5432
