apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: k8squest
  labels:
    app: frontend
    tier: web
spec:
  containers:
  - name: frontend
    image: busybox:1.36
    command: ['sh', '-c', 'while true; do wget -q -O- http://backend-service:8080/api 2>&1; sleep 5; done']
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: k8squest
  labels:
    app: backend
    tier: api
spec:
  containers:
  - name: backend
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=API Response: Success"
      - "-listen=:8080"
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: k8squest
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
  namespace: k8squest
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: admin-tool  # ❌ WRONG! Only allows traffic from "admin-tool", not "frontend"
    ports:
    - protocol: TCP
      port: 8080
