apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: k8squest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ["-text=Version GREEN (NEW)", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: k8squest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ["-text=Version BLUE (OLD)", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: k8squest
spec:
  selector:
    app: myapp
    version: blue  # PROBLEM! Still pointing to OLD version!
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
