apiVersion: v1
kind: Pod
metadata:
  name: client-app
  namespace: default  # Wrong namespace!
  labels:
    app: client
spec:
  containers:
  - name: client
    image: busybox:latest
    command: ['sh', '-c', 'while true; do sleep 3600; done']
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default  # Wrong namespace!
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
