---
apiVersion: v1
kind: Namespace
metadata:
  name: k8squest
---
# ✅ FIXED: Headless service (clusterIP: None) provides per-pod DNS
# Now each pod gets: <pod-name>.<service-name>.<namespace>.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: web-cluster
  namespace: k8squest
spec:
  clusterIP: None  # ✅ Headless service - no virtual IP!
  selector:
    app: web-cluster
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: k8squest
spec:
  serviceName: web-cluster  # Must match headless service name
  replicas: 3
  selector:
    matchLabels:
      app: web-cluster
  template:
    metadata:
      labels:
        app: web-cluster
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: web

# ✅ Now DNS works:
# web-0.web-cluster.k8squest.svc.cluster.local → web-0 pod
# web-1.web-cluster.k8squest.svc.cluster.local → web-1 pod
# web-2.web-cluster.k8squest.svc.cluster.local → web-2 pod
