---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: k8squest
type: Opaque
data:
  username: admin  # ❌ Plain text, should be base64!
  password: secretpass123  # ❌ Plain text, should be base64!
---
apiVersion: v1
kind: Pod
metadata:
  name: database-client
  namespace: k8squest
spec:
  containers:
  - name: client
    image: busybox:1.36
    command:
    - sh
    - -c
    - |
      echo "Connecting to database..."
      echo "Username: $DB_USER"
      echo "Password length: ${#DB_PASS}"
      
      # Validate credentials format
      if ! echo "$DB_USER" | grep -q '^[a-zA-Z0-9_-]\+$'; then
        echo "ERROR: Invalid username format (contains invalid characters)"
        exit 1
      fi
      
      if [ ${#DB_PASS} -lt 8 ]; then
        echo "ERROR: Password too short or malformed"
        exit 1
      fi
      
      echo "Connected successfully!"
      sleep 3600
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
