---
apiVersion: v1
kind: Namespace
metadata:
  name: k8squest
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app
  namespace: k8squest
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
---
# ❌ BROKEN: LoadBalancer type requires cloud provider integration
# In local clusters (kind, minikube, k3d), this stays in Pending state forever
# LoadBalancer services need external load balancer provisioning from cloud providers
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: k8squest
spec:
  type: LoadBalancer  # ❌ Won't work in local clusters!
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
