apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: k8squest
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: k8squest
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
