apiVersion: v1
kind: Pod
metadata:
  name: hungry-app
  namespace: k8squest
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
