apiVersion: v1
kind: Pod
metadata:
  name: web-with-init
  namespace: k8squest
spec:
  initContainers:
  - name: wait-for-service
    image: busybox:latest
    command: ['sh', '-c', 'until nslookup nonexistent-service; do echo waiting; sleep 2; done']
  containers:
  - name: web
    image: nginx:latest
    ports:
    - containerPort: 80
