apiVersion: v1
kind: Pod
metadata:
  name: web-with-init
  namespace: k8squest
spec:
  initContainers:
  - name: setup-config
    image: busybox:latest
    command: ['sh', '-c', 'echo "Config ready" > /work-dir/config.txt']
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  containers:
  - name: web
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    emptyDir: {}
