apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
  namespace: k8squest
spec:
  replicas: 5  # PROBLEM! Should be 9 for 90% traffic
  selector:
    matchLabels:
      app: myapp
      track: stable
  template:
    metadata:
      labels:
        app: myapp
        track: stable
        version: v1
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ["-text=Stable v1", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  namespace: k8squest
spec:
  replicas: 5  # PROBLEM! Should be 1 for 10% traffic
  selector:
    matchLabels:
      app: myapp
      track: canary
  template:
    metadata:
      labels:
        app: myapp
        track: canary
        version: v2
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ["-text=Canary v2", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: k8squest
spec:
  selector:
    app: myapp  # Matches BOTH stable and canary
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
