---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage
  namespace: k8squest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-ssd  # ❌ This StorageClass doesn't exist!
---
apiVersion: v1
kind: Pod
metadata:
  name: data-processor
  namespace: k8squest
spec:
  containers:
  - name: processor
    image: busybox:1.36
    command: ['sh', '-c', 'echo "Processing data..." && sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: app-storage
