---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # ✅ Allow multiple pods to mount!
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: k8squest
spec:
  accessModes:
    - ReadWriteMany  # ✅ Request multi-pod access
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-servers
  namespace: k8squest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: shared-content
        persistentVolumeClaim:
          claimName: shared-pvc
