apiVersion: v1
kind: Pod
metadata:
  name: web-app-1
  namespace: k8squest
  labels:
    app: web
spec:
  containers:
  - name: app
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=Pod 1 ready"
      - "-listen=:8080"
    ports:
    - containerPort: 8080
    readinessProbe:          # ✅ ADDED: Readiness probe
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app-2
  namespace: k8squest
  labels:
    app: web
spec:
  containers:
  - name: app
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=Pod 2 ready"
      - "-listen=:8080"
    ports:
    - containerPort: 8080
    readinessProbe:          # ✅ ADDED: Readiness probe
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: k8squest
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: k8squest
spec:
  containers:
  - name: client
    image: busybox:1.36
    command: ['sh', '-c', 'while true; do echo "Request:"; wget -q -O- --timeout=2 http://web-service 2>&1 || echo "Failed"; sleep 2; done']
